# Generated by Django 2.2.7 on 2019-12-30 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=200)),
                ('times_per_year', models.DecimalField(decimal_places=6, max_digits=10)),
                ('times_per_month', models.DecimalField(decimal_places=6, max_digits=10)),
                ('times_per_week', models.DecimalField(decimal_places=6, max_digits=10)),
                ('times_per_day', models.DecimalField(decimal_places=6, max_digits=10)),
                ('period', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('iName', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.BudgetCategory')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.BudgetSchedule')),
            ],
        ),
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iRate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('date', models.DateField(auto_now=True)),
                ('refAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='lastDatum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.AccountData'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.AccountType'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
