# Generated by Django 2.2.7 on 2020-01-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetschedule',
            name='times_per_day',
        ),
        migrations.RemoveField(
            model_name='budgetschedule',
            name='times_per_month',
        ),
        migrations.RemoveField(
            model_name='budgetschedule',
            name='times_per_week',
        ),
        migrations.RemoveField(
            model_name='budgetschedule',
            name='times_per_year',
        ),
    ]
