# Generated by Django 2.2.7 on 2020-04-03 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200101_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='budgetitem',
            old_name='iName',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='user',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='id',
            field=models.AutoField(auto_created=True, default=999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.BudgetCategory'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.BudgetSchedule'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Budget'),
        ),
    ]
