# Generated by Django 2.2.7 on 2020-01-25 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_date', models.DateField(default=datetime.date(2020, 1, 25))),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('body', models.TextField()),
            ],
        ),
    ]
